apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: fitcheck-backend
spec:
  selector:
    app: fitcheck-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP